### ISSUE TITLE
请问API_KEY要如何申请？

### ISSUE THREAD

**Issue by zhaoyouqi** [xdtianyu/PhoneNumber#1]
我在 http://safe.baidu.com/ 没有找到申请API_KEY的入口……好像只能通过留言的方式和他们联系。
请问个人开发者要如何申请API_KEY，需要什么资质呢？

**Comment by xdtianyu** [comment]
`http://apistore.baidu.com/astore/usercenter` 就是里边那个`apikey`。调用的`api`在这里 `http://apistore.baidu.com/apiworks/servicedetail/1398.html`

**Comment by zhaoyouqi** [comment]
谢谢！
