### ISSUE TITLE
功能建议二则

### ISSUE THREAD

**Issue by blueset** [xdtianyu/PhoneNumber#4]
- [ ] 添加「不对联系人弹窗/提醒标记」的开关
- [ ] 对于主动标记，添加「查看/取消忽略号码」的功能

**Comment by xdtianyu** [comment]
应该是 [CallerInfo](https://github.com/xdtianyu/CallerInfo) 这个项目吧， PhoneNumber 只是号码库

**Comment by blueset** [comment]
哦哦，手机发 issue 没注意看，Sorry
